"""
Project 71 -- power and measurement-attenuation analysis. Generates notebook/power_analysis.md.

WHICH PAPER NUMBER: none directly. It decides whether the numbers we are about to spend three
weeks producing can answer the question we pre-registered, and it is written BEFORE the arms
exist so that "underpowered" is a pre-registered finding rather than a post-hoc excuse.

Three things it computes:

 1. MDE -- the smallest true effect detectable at 80% power, alpha 0.05, for the paired
    designs we actually use, at n=180 (primary) and n=60 (crisis co-primary, over-refusal).
 2. POWER at the pre-registered thresholds (10-point ASR reduction, 5-point over-refusal
    tolerance), by Monte Carlo over the exact paired procedure, not a normal approximation.
 3. ATTENUATION -- the ASR judge has recall r < 1, so an observed effect is approximately
    r x the true effect. Includes the case the audit raised: what a ZERO true effect measures
    as when the two arms' recalls differ.

Usage:  python Scripts\\power_analysis.py
"""

import json
import math
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parent.parent
RNG = np.random.default_rng(20260801)
N_SIM = 4000
N_PERM = 2000
ALPHA = 0.05


def perm_p(diff, n_perm=N_PERM, rng=RNG):
    obs = diff.mean()
    signs = rng.integers(0, 2, size=(n_perm, diff.size)) * 2 - 1
    null = (signs * diff).mean(axis=1)
    return (np.sum(np.abs(null) >= abs(obs) - 1e-12) + 1) / (n_perm + 1)


def power_paired(n, p_base, delta, n_seeds=3, n_sim=N_SIM, rng=RNG):
    """Monte Carlo power of the exact procedure we ship: per-prompt seed mean + sign-flip.

    Per-prompt failure probabilities are drawn from a Beta with the target mean and moderate
    dispersion, because real prompts are not exchangeable coin flips -- some are attacked
    successfully by every arm and some by none, and that heterogeneity is what the paired
    design exploits. The treatment shifts each prompt's probability by `delta`, clipped.
    """
    p_treat = max(0.0, min(1.0, p_base + delta))
    conc = 4.0   # Beta concentration; lower = more heterogeneous prompts
    hits = 0
    for _ in range(n_sim):
        a = max(p_base * conc, 1e-3)
        b = max((1 - p_base) * conc, 1e-3)
        pb = rng.beta(a, b, size=n)
        shift = p_treat - p_base
        pt = np.clip(pb + shift, 0.0, 1.0)
        bm = rng.binomial(n_seeds, pb) / n_seeds
        tm = rng.binomial(n_seeds, pt) / n_seeds
        if perm_p(tm - bm, rng=rng) <= ALPHA:
            hits += 1
    return hits / n_sim


def mde(n, p_base, n_seeds=3, target=0.80, lo=0.01, hi=0.60):
    """Smallest |delta| (a REDUCTION) reaching `target` power. Bisection on the simulator."""
    if power_paired(n, p_base, -hi, n_seeds) < target:
        return None
    for _ in range(7):
        mid = (lo + hi) / 2
        if power_paired(n, p_base, -mid, n_seeds) >= target:
            hi = mid
        else:
            lo = mid
    return hi


def main():
    out = []
    W = out.append

    W("# Power and measurement attenuation — Project 71\n")
    W("**Written 2026-08-01, before B3, T or T_ctrl were scored.** Generated by")
    W("`scripts/power_analysis.py`; re-run it to reproduce every number here.\n")
    W("Required by the pre-lock audit. The point of writing it now is that if we are")
    W("underpowered for our own pre-registered effect, that is a **pre-registered finding**,")
    W("not something discovered after the numbers disappoint.\n")

    W("## 0. The headline conclusion\n")

    # ---------- attenuation ----------
    W("## 1. Measurement attenuation — the dominant term\n")
    W("The ASR judge has precision 1.00 and **recall 0.55** (n=36, inter-model agreement —")
    W("see the label-provenance correction). With precision 1 and recall r, an arm whose true")
    W("failure rate is p is measured at `r * p`. So a true difference D is observed as")
    W("`r * D`:\n")
    W("| true ASR reduction | observed at r=0.45 | r=0.55 (ours) | r=0.65 |")
    W("|---|---|---|---|")
    for d in (5, 10, 15, 20, 25):
        W(f"| {d} pts | {0.45*d:.1f} | **{0.55*d:.1f}** | {0.65*d:.1f} |")
    W("")
    W("**A true 10-point reduction — exactly our pre-registered minimum meaningful effect —")
    W("is measured as 5.5 points and therefore FAILS our own threshold.** The threshold and")
    W("the instrument are inconsistent. Either the threshold is restated on the observed")
    W("scale (a 10-point *observed* reduction implies ~18 points true), or reported effects")
    W("are attenuation-corrected with the recall CI propagated. Correcting is not free:")
    W("recall 0.55 has 95% CI [0.29, 0.76] from n=36, so dividing by it inflates the")
    W("interval substantially.\n")

    W("### 1b. The asymmetric case the audit raised\n")
    W("The withdrawn claim was that the under-count is identical across arms. It is not")
    W("guaranteed: our own pinned lock records that this judge under-counts *terse* arms, and")
    W("arms differ in terseness. If the two arms are measured at different recalls, a **zero**")
    W("true effect is observed as a non-zero one:\n")
    W("| true ASR (both arms) | r_baseline | r_treatment | observed gap |")
    W("|---|---|---|---|")
    for p in (30, 40, 50):
        for rb, rt in ((0.65, 0.45), (0.60, 0.50), (0.55, 0.55)):
            W(f"| {p}% | {rb} | {rt} | **{(rb-rt)*p:+.1f} pts** |")
    W("")
    W("At 40% true ASR and recalls 0.65 vs 0.45, a zero true effect reads as an **8-point**")
    W("reduction — most of our 10-point threshold, manufactured entirely by differential")
    W("measurement. This is not hypothetical for us: B3's delivered turns include a fixed")
    W("decline on filter-replaced items, which is exactly the kind of terse output the judge")
    W("is documented to score differently. **Mitigation in force:** Revision 3 removes the")
    W("judge from those items entirely (deterministic `safe`), which eliminates the largest")
    W("known source of differential recall. What remains is unquantified, and the only real")
    W("fix is per-arm recall estimates — i.e. the human validation set, stratified by arm.\n")

    # ---------- MDE ----------
    W("## 2. Minimum detectable effect\n")
    W("Monte Carlo over the exact shipped procedure (per-prompt seed mean, two-sided paired")
    W(f"sign-flip permutation test, alpha {ALPHA}, 3 seeds, {N_SIM} simulations, heterogeneous")
    W("per-prompt probabilities). MDE = smallest true reduction reaching 80% power.\n")
    W("| endpoint | n | assumed baseline | MDE (true pts) | MDE as OBSERVED at r=0.55 |")
    W("|---|---|---|---|---|")
    rows = []
    for label, n, p0 in (("primary ASR (non-crisis)", 180, 0.40),
                         ("primary ASR (non-crisis)", 180, 0.25),
                         ("crisis co-primary", 60, 0.50),
                         ("over-refusal", 60, 0.20)):
        m = mde(n, p0, n_seeds=3)
        obs = None if m is None else m * 0.55
        rows.append((label, n, p0, m, obs))
        W(f"| {label} | {n} | {p0:.0%} | "
          f"{'>60' if m is None else f'{m*100:.1f}'} | "
          f"{'--' if obs is None else f'{obs*100:.1f}'} |")
    W("")
    W("**The endpoint split raised the MDE**, and this is a real cost of Revision 6 that must")
    W("be stated: the primary endpoint went from 240 pooled items to 180, so the MDE rises by")
    W("roughly sqrt(240/180) = 1.15x. That was accepted knowingly — a well-powered test of an")
    W("incoherent quantity is worth less than a slightly weaker test of a coherent one, since")
    W("pooling averaged over two opposite refusal conventions.\n")

    # ---------- power at thresholds ----------
    W("## 3. Power at the pre-registered thresholds\n")
    W("| endpoint | n | baseline | true effect | power |")
    W("|---|---|---|---|---|")
    pw = {}
    for label, n, p0, d in (("primary ASR", 180, 0.40, -0.10),
                            ("primary ASR", 180, 0.40, -0.18),
                            ("primary ASR", 180, 0.25, -0.10),
                            ("crisis co-primary", 60, 0.50, -0.10),
                            ("crisis co-primary", 60, 0.50, -0.20),
                            ("over-refusal", 60, 0.20, +0.05)):
        v = power_paired(n, p0, d, n_seeds=3)
        pw[f"{label} n={n} p0={p0} d={d}"] = v
        W(f"| {label} | {n} | {p0:.0%} | {d*100:+.0f} pts | **{v:.2f}** |")
    W("")
    W("Read these as power against the **true** effect. Because the judge attenuates, the")
    W("effect that actually arrives at the test is ~0.55x the true one, so the operative row")
    W("for a true 10-point effect is the one at -5.5 points, not -10.\n")

    # ---------- over-refusal ----------
    W("## 4. The over-refusal tolerance\n")
    W("The 5-point tolerance is now applied to the POINT ESTIMATE (Revision 6). At n=60 the")
    W("bootstrap 95% half-width on a paired difference is itself of order:\n")
    hw = []
    for p0 in (0.10, 0.20, 0.35):
        sims = []
        for _ in range(600):
            pb = RNG.beta(max(p0*4, 1e-3), max((1-p0)*4, 1e-3), size=60)
            b = RNG.binomial(3, pb)/3
            t = RNG.binomial(3, pb)/3
            d = t - b
            boot = np.array([d[RNG.integers(0, 60, 60)].mean() for _ in range(200)])
            sims.append((np.percentile(boot, 97.5) - np.percentile(boot, 2.5)) / 2)
        hw.append((p0, float(np.mean(sims))))
        W(f"- baseline over-refusal {p0:.0%}: mean half-width **{np.mean(sims)*100:.1f} pts** "
          f"at a TRUE difference of zero")
    W("")
    W("So the old rule — test the CI **upper bound** against 5 points — was unmeetable: the")
    W("upper bound exceeds 5 even when the true difference is exactly zero. Applying the")
    W("tolerance to the point estimate and reporting the interval beside it is the correction.")
    W("It also means **a point estimate inside the tolerance is weak evidence of a bounded")
    W("cost** whenever the interval is wider than the tolerance; `stats.py` emits exactly that")
    W("warning automatically.\n")

    # ---------- conclusion ----------
    concl = [
        "## 5. Honest conclusion\n",
        "**We are underpowered for the effect we pre-registered, and the binding constraint is",
        "the instrument rather than the sample size.**\n",
        "1. Judge recall 0.55 attenuates every effect by ~45%. A true 10-point reduction —",
        "   our pre-registered minimum meaningful effect — arrives at the test as ~5.5 points.",
        f"2. At n=180 and a 40% baseline, power against a true 10-point effect is "
        f"{pw.get('primary ASR n=180 p0=0.4 d=-0.1', float('nan')):.2f}; against the ~18-point",
        "   true effect that would be needed to *observe* 10 points, it is",
        f"   {pw.get('primary ASR n=180 p0=0.4 d=-0.18', float('nan')):.2f}.",
        "3. The crisis co-primary at n=60 is materially weaker again.",
        "4. Differential recall between arms can manufacture an ~8-point apparent effect from",
        "   nothing, which is comparable to the effect we are hunting.\n",
        "**What this does NOT mean.** It does not mean the experiment is not worth running. A",
        "bounded null is a publishable result and the pre-registration already says so. It",
        "means we must (a) report the attenuation explicitly beside every ASR figure, (b) not",
        "claim a null is evidence of no effect when we are powered only for a large one, and",
        "(c) treat the filter-attributable vs model-generated decomposition — which is a",
        "*composition*, not a difference of two noisy rates — as the result most likely to",
        "survive scrutiny.\n",
        "**Recommended, for the main thread to decide:** restate the ASR threshold on the",
        "observed scale, or report attenuation-corrected effects with the recall CI",
        "propagated. Doing neither leaves a threshold that the instrument cannot deliver.\n",
    ]
    out[out.index("## 0. The headline conclusion\n") + 1: out.index("## 0. The headline conclusion\n") + 1] = [
        "**We are underpowered for our pre-registered 10-point ASR effect, and the binding",
        "constraint is judge recall (0.55), not sample size.** A true 10-point reduction is",
        "measured as ~5.5 points and would fail our own threshold. Details and the recommended",
        "correction are in §5.\n",
    ]
    out.extend(concl)

    dest = REPO / "notebook" / "power_analysis.md"
    dest.write_text("\n".join(out), encoding="utf-8")
    print("\n".join(out[:0]))
    print(f"[written] {dest}")
    print(json.dumps({k: round(v, 3) for k, v in pw.items()}, indent=1))


if __name__ == "__main__":
    main()
